services:
  # My Web Application
  webapp:
    build: .
    expose:
      - "3000"
    volumes:
      - ./server/images:/app/images
      - ./server/thumbnails:/app/thumbnails
    networks:
      - webnet

  # Reverse proxy
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/conf.d/options:/etc/nginx/options:ro
      - ./nginx/www:/usr/share/nginx/html
    depends_on:
      - webapp
    networks:
      - webnet

  # Helper to obtain and renew certificates
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
