services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/images:/app/images
      - ./server/thumbnails:/app/thumbnails
