[package]
name = "server"
version = "0.2.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.6", features = ["multipart"] }
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
serde = { version = "1.0.210", features = ["derive"] }
hyper = {version = "1.4.1", features = ["full"] }
tower-http = { version = "0.6.1", features = ["cors"] }
tower = "0.5.1"
thiserror = "1.0.64"
serde_json = "1.0.128"
tracing = "0.1.40"
image = "0.25.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
