[package]
name = "server"
version = "0.3.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.6", features = ["multipart"] }
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
serde = { version = "1.0.210", features = ["derive"] }
hyper = {version = "1.4.1", features = ["full"] }
tower-http = { version = "0.6.1", features = ["cors"] }
image = "0.25.4"
tower = "0.5.1"
thiserror = "1.0.64"
serde_json = "1.0.128"
dotenv = "0.15.0"
chrono = "0.4.39"
jsonwebtoken = "9.3.0"
bcrypt = "0.16.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
